import type { CommitType } from '@/types/modules/commit';

const DEFAULT_COMMIT_TYPES: CommitType[] = [
	{ name: 'feat', emoji: '✨', code: ':sparkles:', description: 'Introducing new features' },
	{ name: 'fix', emoji: '🐛', code: ':bug:', description: 'Fixing a bug' },
	{ name: 'refactor', emoji: '♻️', code: ':recycle:', description: 'Refactoring code' },
	{ name: 'perf', emoji: '⚡️', code: ':zap:', description: 'Improving performance' },
	{ name: 'clean', emoji: '🧹', code: ':broom:', description: 'Cleaning up code' },
	{ name: 'security', emoji: '🔒', code: ':lock:', description: 'Fixing security issues' },
	{ name: 'docs', emoji: '📝', code: ':memo:', description: 'Updating documentation' },
	{ name: 'test', emoji: '✅', code: ':white_check_mark:', description: 'Adding or updating tests' },
	{ name: 'build', emoji: '👷', code: ':construction_worker:', description: 'Updating build scripts' },
	{ name: 'remove', emoji: '🔥', code: ':fire:', description: 'Removing code or files' },
	{ name: 'style', emoji: '💄', code: ':lipstick:', description: 'Updating styles or UI' },
	{ name: 'config', emoji: '🔧', code: ':wrench:', description: 'Updating configuration' },
	{ name: 'upgrade', emoji: '⬆️', code: ':arrow_up:', description: 'Upgrading dependencies' },
	{ name: 'downgrade', emoji: '⬇️', code: ':arrow_down:', description: 'Downgrading dependencies' },
	{ name: 'i18n', emoji: '🌐', code: ':globe_with_meridians:', description: 'Localization updates' },
	{ name: 'init', emoji: '🎉', code: ':tada:', description: 'Initial commit' },
	{ name: 'deploy', emoji: '🚀', code: ':rocket:', description: 'Deploying application' },
	{ name: 'db', emoji: '🗃️', code: ':card_file_box:', description: 'Database changes' },
	{ name: 'ux', emoji: '🚸', code: ':children_crossing:', description: 'Improving UX/UI' },
	{ name: 'revert', emoji: '⏪', code: ':rewind:', description: 'Reverting changes' },
	{ name: 'breaking', emoji: '💥', code: ':boom:', description: 'Introducing breaking changes' },
	{ name: 'flag', emoji: '🚩', code: ':triangular_flag_on_post:', description: 'Feature flags updates' },
	{ name: 'a11y', emoji: '♿️', code: ':wheelchair:', description: 'Accessibility improvements' },
	{ name: 'seo', emoji: '🔍', code: ':mag:', description: 'SEO improvements' },
	{ name: 'analytics', emoji: '📈', code: ':chart_with_upwards_trend:', description: 'Adding analytics' },
	{ name: 'mock', emoji: '💾', code: ':floppy_disk:', description: 'Adding or updating mock data' },
	{ name: 'api', emoji: '🔌', code: ':electric_plug:', description: 'API updates' },
	{ name: 'prune', emoji: '🗑️', code: ':wastebasket:', description: 'Removing unused dependencies' },
	{ name: 'typo', emoji: '✏️', code: ':pencil2:', description: 'Fixing typos' },
	{ name: 'review', emoji: '🔍️', code: ':mag_right:', description: 'Changes after code review' },
	{ name: 'experiment', emoji: '🧪', code: ':test_tube:', description: 'Experimental code' },
	{ name: 'pkg', emoji: '📦', code: ':package:', description: 'Updating package files' },
	{ name: 'animation', emoji: '🎨', code: ':art:', description: 'Adding or updating animations' },
	{ name: 'script', emoji: '📜', code: ':scroll:', description: 'Adding custom scripts' },
	{ name: 'struct', emoji: '🏗️', code: ':building_construction:', description: 'Improving code structure' },
	{ name: 'ci', emoji: '🔄', code: ':arrows_counterclockwise:', description: 'Updating CI/CD' },
	{ name: 'legal', emoji: '⚖️', code: ':balance_scale:', description: 'Legal compliance updates' },
	{ name: 'fix-ci', emoji: '🚑', code: ':ambulance:', description: 'CI/CD fix' },
	{ name: 'monitor', emoji: '🔍️', code: ':mag:', description: 'Monitoring or logs update' },
	{ name: 'support', emoji: '📞', code: ':telephone_receiver:', description: 'Adding support for feature' },
	{ name: 'task', emoji: '📌', code: ':pushpin:', description: 'Task management' },
	{ name: 'arch', emoji: '🏛️', code: ':classical_building:', description: 'Architectural changes' },
];

export default DEFAULT_COMMIT_TYPES;
